"""tablas iniciales: pedidos e incidencias

Revision ID: ad4b8fe58f67
Revises: 
Create Date: 2026-09-16 16:57:25.616090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4b8fe58f67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('remitente', sa.String(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=True),
    sa.Column('cuerpo_mensaje', sa.Text(), nullable=False),
    sa.Column('tipo_incidencia', sa.String(), nullable=True),
    sa.Column('urgencia', sa.String(), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('numero_pedido', sa.String(), nullable=True),
    sa.Column('sospechoso', sa.Boolean(), nullable=True),
    sa.Column('discrepancia', sa.Text(), nullable=True),
    sa.Column('motivo_decision', sa.Text(), nullable=True),
    sa.Column('motivo_verificacion', sa.Text(), nullable=True),
    sa.Column('respuesta_borrador', sa.Text(), nullable=True),
    sa.Column('respuesta_final', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_estado'), 'incidencias', ['estado'], unique=False)
    op.create_index(op.f('ix_incidencias_numero_pedido'), 'incidencias', ['numero_pedido'], unique=False)
    op.create_index(op.f('ix_incidencias_thread_id'), 'incidencias', ['thread_id'], unique=True)
    op.create_table('pedidos',
    sa.Column('numero_pedido', sa.String(), nullable=False),
    sa.Column('titular_email', sa.String(), nullable=False),
    sa.Column('transportista', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('tiene_foto', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('numero_pedido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_incidencias_thread_id'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_numero_pedido'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_estado'), table_name='incidencias')
    op.drop_table('incidencias')
    # ### end Alembic commands ###
